spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  profiles:
    include: dev-secret, aws

  config:
    use-legacy-processing: true

logging:
  config: classpath:logback-spring.xml

cloudwatch:
  log_group:
    /tyf/logs/app/dev