spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/tyf;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  flyway:
    baseline-version: 0
    baseline-on-migrate: true
    enabled: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  profiles:
    include: dev-secret, aws

  config:
    use-legacy-processing: true

logging:
  config: classpath:logback-spring.xml

cloudwatch:
  log_group:
    /tyf/logs/app/dev